### ISSUE TITLE
Unexpected token on Line 51 in walletController.js causes connection timeout

### ISSUE THREAD

**Issue by AnotherSii** [Lamden/lamden_wallet_controller#1]
Ran into this issue when I was trying to deploy on Netlify. Used npm to install lamden_wallet_controller.

![lwc_error_0001](https://user-images.githubusercontent.com/60057228/104106932-d0a02080-526d-11eb-8eaf-f6eabd1ce11f.jpg)

**Comment by AdamGold** [comment]
You need to have webpack 5 for the optional chaining to work.
